### ISSUE TITLE
Confusion between Shop Name and Domain in NewClient

### ISSUE THREAD

**Issue by mibzman** [getconversio/go-shopify#101]
Since New Client takes "shopName", my insinct was to pass Client.Name for that argument when making another new client later in the lifecycle for the same shop.  The value from shopName is actually saved under Client.Domain.  Passing Shop.Name resulted in  a ` invalid memory address or nil pointer dereference` for `u := c.baseURL.ResolveReference(rel)`, since the value passed was not a url.

I'm just posting this in case someone else does this, although perhaps there could be a function that builds a new client from a Shop object.

**Comment by dlebech** [comment]
@mibzman I've updated [the documentation for the `NewClient` function](https://godoc.org/github.com/getconversio/go-shopify#NewClient) to make it clear that it expects a `*.myshopify.com` domain but that you can leave out the `.myshopify.com` part like in the example of the README. Hope this helps :-)
