### ISSUE TITLE
Add Create/Update/Delete Product

### ISSUE THREAD

**Issue by jerairrest** [getconversio/go-shopify#21]

**Comment by sudomake** [comment]
**Is it preferable to:**

- create a new Product
- pass the Product to a create function
- create a new Product from the Shopify response
- return the new Product

**or:**

- pass data to a create function
- create a new Product from the Shopify response
- return the new Product

**Comment by dlebech** [comment]
@sudomake the way the library is designed right now, your examples are similar. You can make you own custom product struct and use the client's `Post` method, **or** you can use the already-defined `Product` struct.

For creating a product, I would suggest adding a method similar to [this one](https://github.com/getconversio/go-shopify/blob/9c4e7782a0067b3634d3c03c5cc9dc9a09e7b31c/webhook.go#L78-L86). That would correspond to your first suggestion.

**Comment by dlebech** [comment]
This issue is resolved after @sudomake latest PR #41 :beers:
