### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by jerairrest** [getconversio/go-shopify#24]
Hello!

I wanted to get your thoughts on how to rate limit this package? Traditionally I have used the X-Shopify-Shop-Api-Call-Limit to make sure were not going to exceed our call limit for proceeding calls. Should we also return the current state with API calls? Or is there a better way of handling this?

Thanks!

**Comment by dlebech** [comment]
It's good that you bring this up, because it's definitely something this library is lacking at the moment.

I think for the current design, it will be difficult to add the current API call limit to the returned data without breaking the return types of the different functions (e.g. `([]Order, error)` for the order list). What we have mostly done in the past is a more reactive approach: when the API limit is hit and the 429 error is returned, we retry a few times with a delay according to the retry-after parameter.

So my proposal would be to initially add a new error type `RateLimitError` that contains error information specific to the rate limiting and then it is the callers responsibility to react to an error of that type.

**Comment by dlebech** [comment]
I can work on this tomorrow :-)

**Comment by jerairrest** [comment]
That works for now. In an ideal world we could get access to that header so we can limit before we make the call. :) Thanks man.

**Comment by dlebech** [comment]
@jerairrest I've now merged #25 which adds a specific error type for rate limiting as well as the retry-after value to the error struct.

As a sidenote, I also experimented a bit with adding extra call information to the current calls, but as I mentioned in my previous comment, I couldn't implement this without breaking the current interface, and at this stage, I'm not happy about doing that -- at least not on the master branch.

What do you think?

**Comment by jerairrest** [comment]
Sounds good to me! As an alternative, I've checked my own reactive method as well. From my initial testing it seems to work.  Thanks for all your hard work~

```
package shopify

import "errors"

var ErrNotFound = errors.New("Not Found")
var ErrNotValidToken = errors.New("[API] Invalid API key or access token (unrecognized login or wrong password)")
var ErrCallLimitExceeded = errors.New("Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service.")

func ParseError(err error) interface{} {
	switch err.Error() {
	case "Not Found":
		return ErrNotFound
	case "[API] Invalid API key or access token (unrecognized login or wrong password)":
		return ErrNotValidToken
	case "Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service.":
		return ErrCallLimitExceeded
	}

	return err
}
```

```
func findProduct(client *goshopify.Client, req product.FindProductRequest, i int) (*goshopify.Product, error) {
	product, err := client.Product.Get(int(req.ProductID), nil)

	if err != nil {
		if ErrCallLimitExceeded == ParseError(err) && i < 10 {
			i = i + 1
			time.Sleep(400 * time.Millisecond)
			product, err = findProduct(client, req, i)
		}
		return product, err
	}

	return product, nil
}
```

**Comment by romainmenke** [comment]
https://github.com/getconversio/go-shopify/blob/master/goshopify.go#L36

If `client` would be public we could use our own RoundTrippers. Implementing a RoundTripper that follows the algorithm used by Shopify is not that hard.

Allowing us to use our own http.Clients also makes it possible to fiddle with timeouts and other settings.

https://github.com/romainmenke/go-shopify/commit/9413a87c9d6ac82d5f42e9d9d2f7fb6a756e398e

**Comment by jmnsf** [comment]
From someone who's dealt with breached rate limits, I'm not sure including the header in the return will help when any kind of concurrency is at stake. Telling a single client that it should hold off for x seconds will have no effect when 50 other processes are making requests simultaneously. It's also not reasonable (imo) or simple, to mutex every call to the API and enforce the use of the feedback header.

I'm thinking the client should enforce a throttle, and while this library may provide some functionality to help with that on a single-client use case, any serious multi-process use of it will have to get its own custom implementation, potentially with a shared data-store of some sort.

**Comment by romainmenke** [comment]
@jmnsf exposing the `http.Client` would go a long way. It also wouldn't break anything as it would be purely additive.

In case of a single server back-end a simple rate limiter based on [golang.org/x/time/rate](https://godoc.org/golang.org/x/time/rate) would be be perfect as it also has support for bursts of requests.

**Comment by dlebech** [comment]
@romainmenke I've been thinking on this since yesterday, and my only concern with exposing the client is that it just kind of feels a bit wrong, since dealing with the http client is an abstraction the library is trying to remove from the user. That being said, exposing the client shouldn't really hurt anyone as you say. The standard library allows this for the default http client as well. That's actually how httpmock works :slightly_smiling_face: 

Could you make a small PR for this, then I would be happy to include it? Ideally, we would also want a small test or example showing that the client can be replaced if needed :1st_place_medal:

**Comment by romainmenke** [comment]
#45

[article on timeouts](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/)

The default `http.Client` is not ideal in most scenario's as outlined in the article above. Exposing it also makes it possible for implementers to tweak other settings. If implementers want a plug-and-play solution they can leave it as-is.

An example of a rate limited transport which can be used if `http.Client` is exposed.

```go
type rateLimitedRoundTripper struct {
	http.RoundTripper
	limiter *rate.Limiter
}

func newRateLimitedRoundTripper(tripper http.RoundTripper) *rateLimitedRoundTripper {
	return &rateLimitedRoundTripper{
		RoundTripper: tripper,
		limiter:      rate.NewLimiter(2, 40), // default rate limits
	}
}

func (r *rateLimitedRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
	err := r.limiter.Wait(req.Context())
	if err != nil {
		log.Println("-- rate limit hit --")
		return nil, err
	}

	return r.RoundTripper.RoundTrip(req)
}
```

```go
var tr http.RoundTripper = newRateLimitedRoundTripper(http.DefaultTransport)

c := goshopify.NewClient(APP_NAME, SHOP_NAME, SHOP_TOKEN)
c.Client = &http.Client{
	Transport: tr,
}
```

**Comment by dlebech** [comment]
Thanks @romainmenke :trophy: 

@jerairrest since you originally reported this, we now have the special rate limit error from #25 and the ability to use a custom client with built-in rate limiting (if we want to) since #45. Does this cover your use case for rate limiting with Shopify?
