### ISSUE TITLE
Private Apps Use Different Authentication

### ISSUE THREAD

**Issue by sudomake** [getconversio/go-shopify#26]
There are two different types of applications that can access the Shopify APIs.  Both types use different authentication.

## Public applications
Public applications authenticate to Shopify by providing the X-Shopify-Access-Token header field in each HTTP request to the Shopify API. This access token is obtained through an OAuth handshake.  That looks to be what go-shopify supports currently.

## Private applications
Private applications can interact with the Shopify API on behalf of only one particular store. These applications authenticate with Shopify through basic HTTP authentication. The required credentials must be generated from the Shopify admin of the store that you want to connect with your application. [Details](https://help.shopify.com/api/getting-started/authentication/private-authentication)

## Making Requests
Would it be better to have PublicApp/PrivateApp and PublicClient/PrivateClient types to handle both types of authentication?

**Comment by dlebech** [comment]
@sudomake Thanks for reaching out. I think the current client could accommodate private apps by simply including a password field in the App structure. The proposal would be:

1. Add a `Password` field of type `string` to the [`App` struct](https://github.com/getconversio/go-shopify/blob/ef4f475c03eb4b310c6b0d7c572861b30cda0edf/goshopify.go#L24-L29)
2. Add basic auth headers as an alternative to the token [here](https://github.com/getconversio/go-shopify/blob/ef4f475c03eb4b310c6b0d7c572861b30cda0edf/goshopify.go#L131-L133).

For 2., something like this should probably work:

```
if c.token != "" {
  req.Header.Add("X-Shopify-Access-Token", c.token)
} else if c.app.Password != "" {
  // add the basic auth headers for c.app.ApiKey and c.app.Password
}
```
I don't have time to implement this right now, but what do you think of the proposal?

**Comment by dlebech** [comment]
@sudomake, @jared-fraser added private app functionality in #29. The readme has an example of how to initialize private app credentials. I hope this works for you.

I'll close this issue for now :)
