### ISSUE TITLE
Order NoteAttributes can be multiple return types

### ISSUE THREAD

**Issue by jerairrest** [getconversio/go-shopify#35]
Hello!

I don't know if others have witnessed this yet but it looks like Shopify can return either a string, number, or bool as a NoteAttribute Value in an order meaning that unmarshalling into the following struct can lead to an type error.

```
type NoteAttribute struct {
	Name  string `json:"Name"`
	Value string `json:"Value"`
}
```

I'm not 100% sure what we should do to handle this other than manually creating the struct.

**Comment by dlebech** [comment]
@jerairrest that's a good catch. As far as I know, the only way to get around something like that is then to use `interface{}` as the type of `Value`. Do you have an example of an order where this happened?

**Comment by jerairrest** [comment]
I can't seem to track one down right now. :(

I'll try to reproduce later

**Comment by dbertouille** [comment]
Hey there.

So I captured an order where this happened. I can't supply the whole order here but I can say that the below attribute is being added by another application.

```
    "note_attributes": [
        {
            "name": "Order_Count",
            "value": 1
        }
    ],
```

As you mentioned the only way I can think around this would be to use interface. 

For now, as a work around, I'm going to try pre-processing the data the to convert any integer note attributes to strings. Of course this could be an issue if you cared about the type.

**Comment by dlebech** [comment]
Thanks for sharing this @dbertouille. I guess when it comes to inconsistencies like this, the only way to go in Go (pun intended :slightly_smiling_face: ) is to user `interface{}`. That would at least make sure no errors are thrown during de-serialization, but it won't be nice to have to cast to a specific type in the code using this.

**Comment by dlebech** [comment]
@jerairrest @dbertouille the value field was updated to `interface{}` in #65 . I hope this works for you. I'll close this issue for now.
