### ISSUE TITLE
IDs should use int64 instead of int

### ISSUE THREAD

**Issue by orian** [getconversio/go-shopify#92]
For some objects Shopify is using a global ID space and recently the threshold of 2^31-1 has been exceeded.

The Go's int size is at least 32 bits, but not guaranteed to be bigger (e.g. `int64`).

I propose to switch all `int` ids into `int64`.

**Comment by dlebech** [comment]
Thanks for bringing this up. This was on my mind as well when I initially created the library. The reason I went with `int` was simplicity and the fact that I don't expect anyone to run 32 bit Go servers (It is my understanding that if a 64-bit processor is available, `int` will always be a 64 bit integer.) Of course, this could be the wrong assumption, and I would be curious to know what the best practice is currently (I'm a bit out of touch 🙂 ) *and* whether changing all `int`s to `int64` will actually be a breaking change in the library. `int` and `int64` are different types, after all 🤔

**Comment by orian** [comment]
It would break a library's API. It would make sense to version a library (add a tag) and introduce a change in version 2.
As far as my experience if the numbers are expected to be > 32 bits, the only way to guarantee that software does not break is to use int64.
I can imagine a situation when some magic is introduce in processors so smaller numbers are processed faster and Go team decides to change the size of int (as the language spec allows the compiler to choose int size).

**Comment by dlebech** [comment]
It's a good point about the language spec. I honestly don't know what the best way forward is here. Perhaps we can let this brew for a few days so the community (if they are listening) can voice their support or concerns.

I've almost always used Go vendoring, so a change like this would only break my work when I updated the library locally but not on a production server, but I'm not sure this is 100% ubiquitous in the community yet (?), and if it isn't, I'm not sure that just tagging something as "v2" will do any good?

**Comment by nelz9999** [comment]
SemVer the releases!

**Comment by andrewhoff** [comment]
This issue was moved to bold-commerce/go-shopify#7
